### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by igochkov** [igochkov/vscode-ebnf#1]
Remove all images from the package but the icon. Reference them from other location.

**Comment by Leedehai** [comment]
Hi, can I just delete the image directory from the package directory after installing the package? It doesn't affect the functionality, I assume? Thanks!
Great package! I thought nobody would write a package for EBNF..

**Comment by igochkov** [comment]
Happy to hear you like the package. 
I guess you can delete the directory, but why deleting it ones it's already on your PC? 
The issue here was to reduce the package size in order to send less bits throuw the wire durring install.
