### ISSUE TITLE
Formatting Issues

### ISSUE THREAD

**Issue by sten-code** [igochkov/vscode-ebnf#10]
### Installed product versions
- Visual Studio Code: 1.83.1
- This extension: 1.3.0

### Description
Formatting does really weird stuff with escaping and the | symbol if the newline option is turned off

#### Weird | Formatting

- Write `letter = "A" | "B" | "C" | "D" | "E" | "F";`
- Press Alt+Shift+F
- It now for some reason removed all the spaces before the |
  - So now it would be `letter = "A"| "B"| "C"| "D"| "E"| "F";`

#### Not being able to write "\\"

- Write a term like `"\\", "\\\\\\", '\\', "\", '\', '\\\\'`, it literally doesn't matter how many backslashes
- Press Alt+Shift+F
- Now it just completely deleted all the \ inside the terms

### Current behavior
Explained above

### Expected behavior
Not do that

**Comment by igochkov** [comment]
@sten-code Those issues are fixed in version 1.3.1. 
Can you install the new version and try if the formatting behaves as you expected?

NB: "\" and '\' are not valid strings because backslash is used as an escape character. To be valid you should escape it with a second backslash ("\\" and '\\' ).
