### ISSUE TITLE
Problem with coloring

### ISSUE THREAD

**Issue by dtoffe** [igochkov/vscode-ebnf#18]
### Installed product versions
- Visual Studio Code: 1.89.0
- This extension: 1.3.1

### Description
The coloring is affected by a special '¬' character. Deleting the optional part with that character solves the problem and the coloring works fine again.
![imagen](https://github.com/igochkov/vscode-ebnf/assets/48930784/e3dae468-8a1a-4a71-9cf5-c37e1fc1af05)

### Steps to recreate
1. Copy this snippet into an ebnf file:

``` bnf
special-symbol = '+' | '-' | '*' | '/' | '¬' | '=' | '<' | '>' | '[' | ']' | '.' | ',' | ':' |
                 ';' | '^' | '(' | ')' | '<>' | '<=' | '>=' | ':=' | '..' | 
                 'and' | 'array' | 'begin' | 'case' | 'const' | 'div' | 'do' | 'downto' | 'else' |
              'end' | 'file' | 'for' | 'function' | 'goto' | 'if' | 'in' | 'label' | 'mod' |
              'nil' | 'not' | 'of' | 'or' | 'packed' | 'procedure' | 'program' | 'record' |
              'repeat' | 'set' | 'then' | 'to' | 'type' | 'until' | 'var' | 'while' | 'with' ;
```
### Current behavior
The coloring is incorrect when using the character '¬' in an ebnf option specification.

### Expected behavior
The coloring should be correct for a rule containing that character.

**Comment by igochkov** [comment]
Hi @dtoffe. Thanks for reporting this issue.
I believe I fixed it with the latest changes to the syntax highlighting grammar. This change will be released in version 1.4.0, along with a few more bug fixes.

![image](https://github.com/user-attachments/assets/77ddc4dc-d74c-4f50-8cb8-00d9fc09ce39)
